apiVersion: v1
kind: Service
metadata:
  name: wedding-invitation-external-service
  namespace: wedding-invitation-external
spec:
  selector:
    app: wedding-invitation-external
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
