apiVersion: v1
kind: Service
metadata:
  name: wedding-invitation-service
  namespace: wedding-invitation
spec:
  selector:
    app: wedding-invitation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
